server:
 port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/partner?serverTimezone=GMT%2b8&useSSL=false
    username: root
    password: 132123
    hikari:
      minimum-idle: 10
  #swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    servlet:
      load-on-startup: 1 #启动的时候初始化DispatcherServlet
  mail:
    # 配置 SMTP 服务器地址
    host: smtp.qq.com
    #发送者邮箱
    username: 2707794513@qq.com
    #配置密码，申请码
    password: ydjiyosdeqnndcfg
    #端口号465或587
    port: 587
    #默认的邮件编码
    default-encoding: UTF-8
  redis:
    #Redis数据库索引（默认为0）
    database: 0
    #Redis服务器地址
    host: 127.0.0.1
    #Redis服务器连接端口
    port: 6379
    #Redis服务器连接密码（默认为空）
    #password:
    #连接超时时间
    timeout: 10s
    #缓存池
    lettuce:
     pool:
      #连接池最大发连接数
      max-active: 200
      #连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1ms
      #连接池中的最大空闲连接
      max-idle: 10
      #连接池中的最小空闲连接
      min-idle: 0
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
sa-token:
  token-name: Authorization
  #token有效期，单位s，默认了两小时，-1代表永不过期
  timeout: 7200
  #是否允许同一账号并发登录
  is-share: true
  #token风格
  #token-style: simple-uuid
  #是否输出操作日
  is-log: false
  #token前缀 注意必须是Bearer {token},Bearer后面加空格(令牌类型)
  token-prefix: Bearer
  #jwt密钥
  jwt-secret-key: dsfasdfdadsgad>?:DVFDF>EW":(W21

file:
  upload:
    path: C:\Users\黄一峰\IdeaProjects\partner_back
  download:
    ip: localhost